### ISSUE TITLE
Sound Effects

### ISSUE THREAD

**Issue by hudec117** [hudec117/tic-tac-toe#29]
# User Story
As a player, I want to hear sound effects, so I can receive auditory feedback from the game.

## Acceptance Criteria

- [x] Sound effect for game win.
- [x] Sound effect for game loss.
- [x] Player is able to turn on/off sound effects.

## Solution Notes

- Store audio files in an "audio" folder (src/public/audio)
- `src\public\js\pages\game.mjs` will need modifying (the onGameEnd function specifically)
- Use Vuex store actions to centralise playing sounds?
- Add option for toggling sound effects in Settings page.
- Resources to start learning Vue:
  - https://vuejs.org/v2/guide/
  - https://vuex.vuejs.org/ (after the above)

## Resources

- https://stackoverflow.com/questions/9419263/how-to-play-audio

## Sprint Ready Checklist
1. - [x] Acceptance criteria defined
2. - [x] Team understands acceptance criteria
3. - [x] Team has defined solution / steps to satisfy acceptance criteria
4. - [x] Acceptance criteria is verifiable / testable
5. - [x] External / 3rd Party dependencies identified

**Comment by tomjenk1** [comment]
What audio format do we want the sounds in wav or mp3?

**Comment by hudec117** [comment]
Check browser compatibility for both and choose the most compatible.
